# Example: Call the reusable PR review workflow
# Copy this file to your repo's .github/workflows/ directory

name: Claude PR Review

on:
  issue_comment:
    types: [created]
  pull_request:
    types: [labeled]

# Prevent multiple runs for the same PR
concurrency:
  group: claude-review-${{ github.event.pull_request.number || github.event.issue.number }}
  cancel-in-progress: true

jobs:
  check-trigger:
    # Only run if:
    # 1. Comment is on a PR and contains /review, OR
    # 2. PR was labeled with needs-review
    if: |
      (github.event_name == 'issue_comment' &&
       github.event.issue.pull_request &&
       contains(github.event.comment.body, '/review')) ||
      (github.event_name == 'pull_request' &&
       github.event.label.name == 'needs-review')
    runs-on: ubuntu-latest
    outputs:
      pr_number: ${{ steps.get-pr.outputs.number }}
    steps:
      - name: Get PR number
        id: get-pr
        run: |
          if [[ "${{ github.event_name }}" == "issue_comment" ]]; then
            echo "number=${{ github.event.issue.number }}" >> $GITHUB_OUTPUT
          else
            echo "number=${{ github.event.pull_request.number }}" >> $GITHUB_OUTPUT
          fi

  review:
    needs: check-trigger
    uses: lisk/workflows/.github/workflows/claude-pr-review.yml@main  # Update org/repo name
    with:
      pr_number: ${{ needs.check-trigger.outputs.pr_number }}
      repository: ${{ github.repository }}
      track_progress: false  # Optional: set to true to show progress updates
    secrets:
      claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
